services:
  postgres:
    image: postgres:16-alpine
    container_name: hidro-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: hidro
      POSTGRES_PASSWORD: hidro-segura-cambiar
      POSTGRES_DB: hidro
    ports:
      - "5432:5432"
    volumes:
      - hidro_pgdata:/var/lib/postgresql/data

volumes:
  hidro_pgdata:
